---
language: python
python:
  - "2.7"
  - "3.7"
install:
  - gem install mdl
  - pip install rstcheck
  - pip install sphinx
script:
  # Linting
  # https://github.com/markdownlint/markdownlint
  - mdl -s relaxed README.md
  # https://github.com/myint/rstcheck
  - rstcheck --report warning -r .
